version: "3"
services:
  front:
    image: todolist-app-front
    ports:
      - "3000:80"
    depends_on:
      - back
  back:
    image: todolist-app-back
    environment:
      - MYSQL_HOST=mysqlbd
      - PORT=8080
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
      - MYSQL_DATABASE=todolist
    ports:
      - "8080:8080"
    depends_on:
      - mysqlbd
    restart: always
  mysqlbd:
    image: todolistdb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    restart: always
  